import { Navbar } from "@/components/Navbar/navbar";
import { Inter, Roboto } from "next/font/google";
import './style.css';
const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
      }} suppressHydrationWarning={true} className={roboto.className}>
        <Navbar/>
        {children}
        </body>
    </html>
  );
}
